# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='duration',
            new_name='name',
        ),
    ]
