# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(choices=[('NONE', 'None'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('PESCETARIAN', 'Pescetarian'), ('KOSHER', 'Kosher'), ('HALAL', 'Halal')], max_length=50)),
                ('allegeries_intolerances', models.CharField(choices=[('NONE', 'None'), ('NUTS', 'Nuts'), ('Milk', 'Milk'), ('LACTOSE', 'Lactose'), ('EGG', 'Egg'), ('FISH', 'Fish'), ('SHELLFISH', 'Shellfish'), ('GLUTEN', 'Gluten'), ('SOY', 'Soy'), ('WHEAT', 'Wheat')], max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
