# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-10 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_serving', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fat', models.CharField(default='', max_length=10)),
                ('saturates', models.CharField(default='', max_length=10)),
                ('carbs', models.CharField(default='', max_length=10)),
                ('sugars', models.CharField(default='', max_length=10)),
                ('polyols', models.CharField(default='', max_length=10)),
                ('fibre', models.CharField(default='', max_length=10)),
                ('protein', models.CharField(default='', max_length=10)),
                ('salt', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('brand', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(blank=True, choices=[('DRINKS', 'Drinks'), ('SWEETENERS', 'Sweeteners'), ('SNACKS', 'Snacks'), ('SWEETS', 'Sweets'), ('FOOD', 'Food'), ('SUPPLEMENTS', 'Supplements')], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Ingredients')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='nutritionvalue',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Product'),
        ),
    ]
