# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fat', models.CharField(default='', max_length=10)),
                ('saturates', models.CharField(default='', max_length=10)),
                ('carbs', models.CharField(default='', max_length=10)),
                ('sugars', models.CharField(default='', max_length=10)),
                ('polyols', models.CharField(default='', max_length=10)),
                ('fibre', models.CharField(default='', max_length=10)),
                ('protein', models.CharField(default='', max_length=10)),
                ('salt', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
