# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0004_auto_20200319_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DRINKS', 'drinks'), ('SWEETENERS', 'sweeteners'), ('SWEETS', 'sweets'), ('FOOD', 'food'), ('SUPPLEMENTS', 'supplements')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.ProductCategory'),
        ),
    ]
