# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0007_auto_20200319_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('DRINKS', 'drinks'), ('SWEETENERS', 'sweeteners'), ('SWEETS', 'sweets'), ('FOOD', 'food'), ('SUPPLEMENTS', 'supplements')], max_length=50),
        ),
    ]
