# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0008_auto_20200319_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionvalue',
            old_name='calories',
            new_name='calories_per_serving',
        ),
    ]
