# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0009_auto_20200319_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('DRINKS', 'drinks'), ('SWEETENERS', 'sweeteners'), ('SWEETS', 'sweets'), ('FOOD', 'food'), ('SUPPLEMENTS', 'supplements')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
