# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0011_auto_20200320_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productingredients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Product')),
            ],
        ),
    ]
