# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0012_ingredients_productingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(default='', max_length=75),
        ),
    ]
