# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0013_ingredients_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='productingredients',
        ),
        migrations.AddField(
            model_name='productingredients',
            name='ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Ingredients'),
        ),
    ]
