# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0014_auto_20200322_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='productingredients',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_products.Product'),
        ),
    ]
